let mode;
let modebutton;
let modeinner;
let modepic;
let style;
// let currentUrl = document;

const BACKTOHOME = document.createElement("a");
const CHARSET = document.createElement("meta");
const FOOTER = document.querySelector("footer");
const FOOTERCONTAINER = document.createElement("div"); 
const FOOTERCONTENT = document.createElement("p");
const ICON = document.createElement("link");
const HEAD = document.querySelector("head");
const HEADER = document.querySelector("header");
const HTML = document.querySelector("html");
const LOGO = document.createElement("img");
const MODE = document.createElement("link");
const NAV = document.createElement("nav");
const NAVLIST = document.createElement("ul");
const NLITEM = document.createElement("li");
const RESETSTYLE = document.createElement("link");
const STYLESHEET = document.createElement("link");
const VIEWPORT = document.createElement("meta");